### PR TITLE
Added locale/zh_CN

### PR DESCRIPTION
**Pull request by skys215**
Added simplified Chinese locale files.

### CODE REVIEW

**Comment by skys215** [comment]
@mitulgolakiya Shouldn't the locale file also include `delete` in the `crud.php`? When there's a `create`, usually also has a `delete`.

**Comment by mitulgolakiya** [comment]
@skys215 good catch. Yes, it should have. Please feel free to put a PR. I will merge it in high priority.

**Comment by skys215** [comment]
Does the position of `delete` matters? Should it be at the bottom of the file or it could be anywhere that make sense (after the `back` or `edit`)?

**Comment by mitulgolakiya** [comment]
I don't think so. let's put it after `save`.

**Pull request merged**
