### PR TITLE
5.3

### PR DESCRIPTION
**Pull request by rafaelqm**
Fix on Update Relations of type HasMany

### CODE REVIEW

**Comment by jschlies** [comment]
What is the status this PR??  Parts of this (the relation improvements) look very close to thing I'd like to add. Also, why isn't this PR into develop?? Thanks

**Comment by rafaelqm** [comment]
@jschlies I guess the owner of the project doesn't have analyzed this code, so I started to use my branch, on my repository instead the official repo, referencing this way:
`"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rafaelqm/adminlte-templates"
        },
        {
            "type": "vcs",
            "url": "https://github.com/rafaelqm/laravel-generator"
        }
    ],
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "infyomlabs/laravel-generator": "5.3.x-dev",
        "infyomlabs/adminlte-templates": "5.3.x-dev",
        "infyomlabs/swagger-generator": "dev-master"
    },`

**Comment by jschlies** [comment]
Cool, I have a few pull requests lined up. This is mostly code I developed a year ago or so and now want to sync into this repo. I know that the owner does not have much time repo and that he visited it infrequently.  This is a nice repo and I want it to thrive. I expect to hear something but if I hear nothing in a few weeks, I'll just update my own fork and move on. 

Also, can you explain what you are trying to do in baseRepository->updateRelations() ???

**Comment by rafaelqm** [comment]
@jschlies the baseRepository->updateRelations() is used to save all the related models sent in a same post, i.e. the model Post has a relation with images, with the method:
`public function image(){
    return $this->hasMany(Images::class);
}`

, and in a form you have besides the Post fields, you have many file fields with the name image[], so when you post it, it will save it automatically.
I don't know if you understand, if it isn't clear fell free to contact me in PM and I'll explain more to you.

**Comment by ajayinfyom** [comment]
i think we no longer need of this PR. so closing this PR.

**Pull request closed without merging**
