### PR TITLE
Added option to suppress auto-loader generation.

### PR DESCRIPTION
**Pull request by jschlies**
Added option to suppress auto-loader generation. default is true (generate autoloader)

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
@jschlies `composer dump-autoload -o` is a good option because it will add newly generated files into autoload. so I made it optional like,

` php artisan infyom:api_scaffold Post --skipDumpOptimized`

If you want to skip it then you can use that option.

**Comment by jschlies** [comment]
OK - I will have another Pull request in a day or two

**Comment by mitulgolakiya** [comment]
@jschlies you don't need it. I already did that.

**Comment by jschlies** [comment]
Thanks

**Pull request merged**
