### PR TITLE
Update primary key

### PR DESCRIPTION
**Pull request by mikepsinn**
Update primary key based on database table primary key

### CODE REVIEW

**Comment by ajayinfyom** [comment]
@mikepsinn thank you for your effort.

but we think most of  people use primary key as `id` and if someone has custom primary key then they can use `--primary ` while generating crud.

Like this:
`php artisan infyom:scaffold $MODEL_NAME --fromTable --tableName=$TABLE_NAME --primary=custom_name_id`

**Comment by mikepsinn** [comment]
Got it. Thanks, @ajayinfyom !

This commit just automates the process, but feel free to close it. I will hide my tears. :)

**Comment by ajayinfyom** [comment]
@mikepsinn I have tested your PR.
the problem that the primary key not adding in eloquent Model. 

btw, need to add primary key in Model if the primary key is not `id`

**Comment by mikepsinn** [comment]
Thanks! I'll try to add that to the model.

**Pull request closed without merging**
