### PR TITLE
New select field to pull form another table

### PR DESCRIPTION
**Pull request by phillipmadsen**
depending on what relationship model has with another this will add it to the new select relation dropdown field im working on. I am trying to make it work with your new relationships but i have not been able to find the details to reference them so far. Do you have a list i can use to make these new fields compatable with your new addtions.

example of what im asking for is. 
```
$RELATIONS$
$TABLE_NAME$
$RELATION_TABLE$
```
Anyway let me know. thanks.

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
@phillipmadsen Can you re-create this PR into develop branch ?

**Comment by NightZpy** [comment]
In my vuejs inner version i have working this feature :3 for many to many and one to many :D

**Comment by NightZpy** [comment]
@mitulgolakiya have access to my private repo.

**Comment by phillipmadsen** [comment]
yes sorry i thought i was on the dev branch

**Comment by mitulgolakiya** [comment]
@NightZpy yes, I  got the access. Thanks.

**Pull request closed without merging**
