### PR TITLE
VueJs Option for CRUD

### PR DESCRIPTION
**Pull request by NightZpy**
## Commands:

- `infyom:vuejs Model` _(Generate CRUD VUEJS)_
- `infyom.publish:vuejs` _(For publish vuejs crud stuff)_
- `infyom:rollback Model vuejs` _(For rollback vuejs crudd stuff)_

## Steps:

0. **Only for** @mitulgolakiya the adminlte-templates pull-request already in the develop branch, please, check!
1. `infyom:publish`
2. Install adminlte-templates (obligatory for now)
3. `infyom.publish:vuejs`
4. `npm install `(for install js require stuff define in package.json)
5. 'infyom:vuejs Model' 
6. run gulp command for generate .js and .css files necessary!

## Missing:

- fieldtype files, only text is adapted to vue js
- error message in client side not automatically generated, instead in fields.blade.php the next message appear: ` Custom rule(required) Message Here`
- Validation types between laravel and vue-validator don't match. 
- VueJs Templates for core-templates, only for adminlte-templates for now.

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
@NightZpy Thanks. I will review this and will merge it soon for next release.

**Comment by NightZpy** [comment]
Hi @mitulgolakiya, post changes make in the branch. Now conflic exists!

**Comment by mitulgolakiya** [comment]
@NightZpy great work. I just merged it into develop and will do throughout testing.

**Comment by NightZpy** [comment]
@mitulgolakiya the fork repo had some conflic, because i use the develop branch before some changes and new features. 

P.D.: I add some new features and fix some issues soon!

**Comment by mitulgolakiya** [comment]
I tried to fix it. But you can test develop branch and submit fixes.

**Comment by NightZpy** [comment]
Yes, just wait for any chance from my current job!

**Comment by mitulgolakiya** [comment]
@NightZpy In first test, getting this error.

`copy(myproject/vendor/infyomlabs/laravel-generator/templates/vuejs/vendor/vue-editable/vue-editable.js): failed to open stream: No such file or directory`

**Comment by NightZpy** [comment]
Oh, .gitignore had vendor/ :(
Already make another pull request for solve that.

**Pull request merged**
